use_frameworks!

platform :ios, '10.0'

target 'YJHSocketManager_Example' do
  pod 'YJHSocketManager', :path => '../'

  target 'YJHSocketManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
